language: scala

scala: 2.12.4

jdk: oraclejdk8

before_script:
  - sudo chmod +x /pppsdb

script:
  - sbt clean coverage test coverageReport
  - sbt coverageAggregate

after_success:
- bash <(sudo su)
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false