language: scala

scala: 2.12.4

jdk: oraclejdk8

script:
  - sbt clean coverage test coverageReport
  - sbt coverageAggregate

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false